[tool.poetry]
name = "personaltwilog"
version = "0.1.0"
description = "personal twilog"
authors = ["shift <fantasy_world4423-git@yahoo.co.jp>"]
license = "MIT LICENSE"
readme = "README.md"

[tool.poetry.dependencies]
isort = "^5.12.0"
mock = "^5.0.1"
pycodestyle = "^2.10.0"
pyppeteer = "^1.0.2"
python = "^3.11,<4.0"
requests = "^2.30.0"
requests-oauthlib = "^1.3.1"
sqlalchemy = "^2.0.12"
requests-html = "^0.10.0"

[tool.isort]
line_length = 256
multi_line_output = 9

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
