[tool.poetry]
name = "personaltwilog"
version = "0.1.0"
description = "personal twilog"
authors = ["shift <fantasy_world4423-git@yahoo.co.jp>"]
license = "MIT LICENSE"
readme = "README.md"

[tool.poetry.dependencies]
httpx = "^0.25.0"
isort = "^5.12.0"
mock = "^5.0.1"
orjson = "^3.9.7"
pycodestyle = "^2.11.0"
python = "^3.11,<4.0"
requests = "^2.31.0"
sqlalchemy = "^2.0.19"
twitter-api-client = "^0.10.11"

[tool.isort]
line_length = 256
multi_line_output = 9

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
